---
eidaws.federator:
  common:
    # logging_conf: ~/work/projects/eidaws/config/logging.conf
    # Absolute StationLite routing URL
    url_routing: 'http://eida-federator.ethz.ch/eidaws/routing/1/query'
    # HTTP connection pool related configuration
    routing_connection_limit: 25
    # Note(damb): # EIDA datacenters is currently 12
    endpoint_connection_limit: 120
    endpoint_connection_limit_per_host: 10
    # Per client retry-budget related configuration
    # Threshold in percent before endpoint requests are being dropped
    client_retry_budget_threshold: 0.5
    client_retry_budget_ttl: 1800
    client_retry_budget_window_size: 4096
    # Number of worker tasks
    pool_size: 20
  fdsnws.station.text:
    url_routing: 'http://eida-federator.ethz.ch/eidaws/routing/1/query'
    # Frontend cache configuration
    cache_config:
      cache_type: 'redis'
      # See https://aioredis.readthedocs.io/en/v1.3.0/api_reference.html#connections-pool
      # for further configuration parameters
      cache_kwargs:
        url: "redis://localhost:6379"
        default_timeout: 43200 
    proxy_netloc:
    # proxy_netloc: '//localhost:8090'
  fdsnws.station.xml:
    url_routing: 'http://eida-federator.ethz.ch/eidaws/routing/1/query'
    # Note(damb): # EIDA datacenters is currently 12
    endpoint_connection_limit: 60
    endpoint_connection_limit_per_host: 5
  fdsnws.dataselect:
    url_routing: 'http://eida-federator.ethz.ch/eidaws/routing/1/query'
  eidaws.wfcatalog:
    url_routing: 'http://eida-federator.ethz.ch/eidaws/routing/1/query'
...
