version: '3.3'
services:
  # eidaws-federator
  federator:
    container_name: eidaws-federator
    image: eidaws-federator:1.0 
    restart: always
    volumes:
      - type: volume
        source: eidaws_federator_log
        target: /var/log/eidaws-federator
        volume:
          nocopy: false
    ports:
      - "8080:8080"

  # eidaws-federator Redis backend
  federator-redis:
    container_name: eidaws-federator-redis
    image: redis:5
    restart: always

volumes:
  eidaws_federator_log:
