---
# -----------------------------------------------------------------------------
# For general configuration options see the exemplary
# eidaws_federator_config.yml.example template configuration file.
#
# ----
# Request method used when performing endpoint requests.
# Allowed values: 'GET' or 'POST'
# Default: 'GET'
#
endpoint-request-method: 'POST'
#
# ----
# Maximum total stream epoch duration in days before returning a HTTP 413
# (Request too large) response.
# Allowed values: None or int (days)
# Default: None
#
max-stream-epoch-duration-total: 330000
#
# -----------------------------------------------------------------------------
# Additional configuration options for the eida-federator-wfcatalog-json
# application which does implement HTTP 413 (Request too large) response
# handling i.e. splitting and aligning facilities.
#
# ----
# Absolute path to a temporary directory where buffers are stored.
# Allowed values: None or absolute path
# Default: None
#
tempdir: /tmp
#
# ----
# Data is buffered using an approach based on spooled temporary files
# (https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile).
# The 'buffer-rollover-size' configuration parameter (in bytes) defines
# when data is buffered on disk. If 0, data is never buffered on disk.
# Default: 0
#
buffer-rollover-size: 2097152  # 2MB
#
# ----
# Splitting factor when performing splitting and aligning for large
# requests.
# Default: 2
#
# splitting-factor: 2
#
...
