---
# For general configuration options see the exemplary
# eidaws_federator_config.yml.example template configuration file.
#
# -----------------------------------------------------------------------------
# Cache specific configuration options
# ----
# Cache configuration. Cache keys are computed based on request parameters
# (including stream epochs). The cache can be configured with different
# caching backends:
#
#   * cache_type: 'null'
#   * cache_type: 'redis'
#
# If None, both response buffering and caching is disabled.
# Default: None
#
# cache-config:
#
# ---
# Exemplary NullCache configuration (i.e. enabled response buffering, no
# caching; e.g. for testing purposes):
#
# cache-config:
#   cache_type: 'null'
#
# ---
# Exemplary Redis configuration:
#
cache-config:
  cache_type: 'redis'
#   
#   Redis cache related configuration options
#
  cache_kwargs:
#
# --
#     Absolute URL to Redis server. Required.
#
      url: 'redis://eidaws-federator-redis:6379/0'
#
# --
#     Cache timeout in seconds. A timeout of 0 indicates that the cache
#     never expires.
#
      default_timeout: 43200
#
# --
#     Compress cached data.
#     Allowed values: boolean
#     Default: True
#
#     compress:
# --
#     Minimum size of the Redis connection pool.
#
#     minsize: 1
#
# --
#     Maximum size of the Redis connection pool.
#
#     maxsize: 10
#
...
