# -*- coding: utf-8 -*-

FDSNWS_QUERY_METHOD_TOKEN = "query"
FDSNWS_QUERYAUTH_METHOD_TOKEN = "queryauth"

FDSNWS_STATION_PATH = "/fdsnws/station/1"
FDSNWS_STATION_PATH_QUERY = "/".join(
    [FDSNWS_STATION_PATH, FDSNWS_QUERY_METHOD_TOKEN]
)
FDSNWS_DATASELECT_PATH = "/fdsnws/dataselect/1"
FDSNWS_DATASELECT_PATH_QUERY = "/".join(
    [FDSNWS_DATASELECT_PATH, FDSNWS_QUERY_METHOD_TOKEN]
)
FDSNWS_DATASELECT_PATH_QUERYAUTH = "/".join(
    [FDSNWS_DATASELECT_PATH, FDSNWS_QUERYAUTH_METHOD_TOKEN]
)
EIDAWS_WFCATALOG_PATH = "/eidaws/wfcatalog/1"
EIDAWS_WFCATALOG_PATH_QUERY = "/".join(
    [EIDAWS_WFCATALOG_PATH, FDSNWS_QUERY_METHOD_TOKEN]
)
EIDAWS_ROUTING_PATH = "/eidaws/routing/1"
EIDAWS_ROUTING_PATH_QUERY = "/".join(
    [EIDAWS_ROUTING_PATH, FDSNWS_QUERY_METHOD_TOKEN]
)

FDSNWS_DEFAULT_NO_CONTENT_ERROR_CODE = 204
FDSNWS_NO_CONTENT_CODES = (FDSNWS_DEFAULT_NO_CONTENT_ERROR_CODE, 404)
FDSNWS_DOCUMENTATION_URI = "http://www.fdsn.org/webservices/"

FDSNWS_QUERY_VALUE_SEPARATOR_CHAR = "="
FDSNWS_QUERY_LIST_SEPARATOR_CHAR = ","
FDSNWS_QUERY_WILDCARD_MULT_CHAR = "*"
FDSNWS_QUERY_WILDCARD_SINGLE_CHAR = "?"

# ----------------------------------------------------------------------------
STATIONXML_NAMESPACES = ("{http://www.fdsn.org/xml/station/1}",)

STATIONXML_ELEMENT_NETWORK = "Network"
STATIONXML_ELEMENT_STATION = "Station"
STATIONXML_ELEMENT_CHANNEL = "Channel"


def _element_to_tags(element):
    return [f"{ns}{element}" for ns in STATIONXML_NAMESPACES]


STATIONXML_TAGS_NETWORK = _element_to_tags(STATIONXML_ELEMENT_NETWORK)
STATIONXML_TAGS_STATION = _element_to_tags(STATIONXML_ELEMENT_STATION)
STATIONXML_TAGS_CHANNEL = _element_to_tags(STATIONXML_ELEMENT_CHANNEL)
