# -*- coding: utf-8 -*-

FDSNWS_QUERY_METHOD_TOKEN = "query"

# FDSN_STATION_PATH = '/fdsnws/station/1'

FDSNWS_DEFAULT_NO_CONTENT_ERROR_CODE = 204
FDSNWS_NO_CONTENT_CODES = (FDSNWS_DEFAULT_NO_CONTENT_ERROR_CODE, 404)
FDSNWS_SERVICE_DOCUMENTATION_URI = "http://www.fdsn.org/webservices/"

FDSNWS_QUERY_VALUE_SEPARATOR_CHAR = "="
FDSNWS_QUERY_LIST_SEPARATOR_CHAR = ","
FDSNWS_QUERY_WILDCARD_MULT_CHAR = "*"
FDSNWS_QUERY_WILDCARD_SINGLE_CHAR = "?"

# ----------------------------------------------------------------------------
STATIONXML_NAMESPACES = ("{http://www.fdsn.org/xml/station/1}",)

STATIONXML_ELEMENT_NETWORK = "Network"
STATIONXML_ELEMENT_STATION = "Station"
STATIONXML_ELEMENT_CHANNEL = "Channel"


def _element_to_tags(element):
    return [f"{ns}{element}" for ns in STATIONXML_NAMESPACES]


STATIONXML_TAGS_NETWORK = _element_to_tags(STATIONXML_ELEMENT_NETWORK)
STATIONXML_TAGS_STATION = _element_to_tags(STATIONXML_ELEMENT_STATION)
STATIONXML_TAGS_CHANNEL = _element_to_tags(STATIONXML_ELEMENT_CHANNEL)
